name: dartcoveralls
version: 0.0.1
author: Ole Martin Gjersvik <olem@olem.org>
description: Tool to upload dart coverage information to coverall.io
dependencies:
  args: any
  git: any
  http: any
  path: any
  yaml: any
dev_dependencies:
  coverage: any
  unittest: any
